name: Upload Files as Artifacts

on:
  push:
    branches:
      - master  # Trigger the workflow when the 'master' branch is updated
  workflow_dispatch:  # Allow manual runs

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository files
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Upload all files from the repository as an artifact
      - name: Upload all files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: IgniteUI_grid-demos-data  # Name of the artifact
          path: |
            **/*       # Upload all files and directories recursively
          retention-days: 2  # How long the artifact should be retained
